# Generated by Django 6.1 on 2026-09-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('observations', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('confirmee', 'Confirmée'), ('effectuee', 'Effectuée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
            ],
        ),
    ]
