# Generated by Django 6.1.1 on 2026-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_activite_entreprise_rendezvous_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activite',
            name='rappel_minutes_avant',
            field=models.CharField(blank=True, choices=[('', 'Aucun rappel'), ('15', '15 minutes avant'), ('30', '30 minutes avant'), ('60', '1 heure avant'), ('1440', '1 jour avant')], max_length=10),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='rappel_minutes_avant',
            field=models.CharField(blank=True, choices=[('', 'Aucun rappel'), ('15', '15 minutes avant'), ('30', '30 minutes avant'), ('60', '1 heure avant'), ('1440', '1 jour avant')], max_length=10),
        ),
    ]
