# Generated by Django 6.1.1 on 2026-09-27 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_activite_rappel_envoye_activite_rappel_minutes_avant_and_more'),
        ('entreprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('participants', models.TextField(blank=True, help_text='Indiquez les participants à la réunion.')),
                ('ordre_du_jour', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunions_creees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reunions', to='entreprises.entreprise')),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunions_organisees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
