# Generated by Django 6.1.1 on 2026-09-28 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_reunion'),
        ('entreprises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_redaction', models.DateField(auto_now_add=True)),
                ('participants', models.TextField(blank=True, help_text='Participants présents à la réunion.')),
                ('resume', models.TextField(blank=True, help_text='Résumé général de la réunion.')),
                ('points_discutes', models.TextField(blank=True, help_text='Principaux points abordés pendant la réunion.')),
                ('decisions', models.TextField(blank=True, help_text='Décisions prises pendant la réunion.')),
                ('actions_a_realiser', models.TextField(blank=True, help_text='Actions ou tâches à réaliser après la réunion.')),
                ('observations', models.TextField(blank=True, help_text='Observations ou informations complémentaires.')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_rendus_crees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comptes_rendus', to='entreprises.entreprise')),
                ('reunion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compte_rendu', to='agenda.reunion')),
            ],
        ),
    ]
