# Generated by Django 6.1.1 on 2026-09-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_compterendu'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reunion',
            name='rappel_minutes_avant',
            field=models.CharField(blank=True, choices=[('', 'Aucun rappel'), ('15', '15 minutes avant'), ('30', '30 minutes avant'), ('60', '1 heure avant'), ('1440', '1 jour avant')], max_length=10),
        ),
    ]
